# Config definitions.

xresources:
    type: colorscheme
    path: "~/.config/xrdb/Xresources.xdefaults"
    regex: '#include ".*\.xdefaults"'
    replace: '#include "./{}.xdefaults"'
    cmd: "reload_xrdb"

vim:
    type: colorscheme
    path: "~/.config/nvim/init.vim"
    regex: 'colorscheme .*'
    replace: "colorscheme {}"

lightline:
    type: colorscheme
    path: "~/.config/nvim/init.vim"
    regex: '    \\   "colorscheme" : .*'
    pre: '    \   "colorscheme" : "{}",'
