# Config definitions.

xresources:
    path: "~/.config/xrdb/Xresources.xdefaults"
    regex: '#include ".*\.xdefaults"'
    pre: '#include "./'
    post: '.xdefaults"'
    cmd: "reload_xrdb"

vim:
    path: "~/.config/nvim/init.vim"
    regex: 'colorscheme .*'
    pre: "colorscheme "
    post: ""

lightline:
    path: "~/.config/nvim/init.vim"
    regex: '    \\   "colorscheme" : .*'
    pre: '    \   "colorscheme" : "'
    post: '",'
